spring.application.name=ad-auction-fairness-engine

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/adauction
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=auction-engine
spring.kafka.consumer.auto-offset-reset=earliest

# Port
server.port=8080